### PR TITLE
Pinning nixpkgs to my current working version

### LINKED ISSUE #2: pin nixpkgs to ensure nix-shell works
Hey, I was checking out your blog post about setting up ghcide. Thought I would
clone your repo and give it a whirl. However, I am running into the following error:

```
λ ~/code/shopping-cart-haskell/ master nix-shell
error: Package ‘refined-0.4.4’ in /nix/store/3m9z2vfr0fnfdgrshyy70cidhyp5wbkz-nixos-20.09pre217537.d96bd3394b7/nixos/pkgs/development/haskell-modules/hackage-packages.nix:202905 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

I think the best solution is to pin nixpkgs to a working revision of the repository.

Here are some links that go into how one might do that:

- https://github.com/Gabriel439/haskell-nix
- https://www.fosskers.ca/blog/nix-en.html
- https://www.haskell.org/cabal/users-guide/nix-integration.html
- https://cah6.github.io/technology/nix-haskell-1/
- https://cah6.github.io/technology/nix-haskell-2/

I haven't been following the latest trends in how to setup Haskell projects with
nix so those might already be out of date. I've noticed some people use
https://input-output-hk.github.io/haskell.nix/, but that might be overkill and
the build times are insane unless you setup cachix and pin to a known revision
that the CI ran for and cached.

I tried this revision of the unstable branch where refined is not marked broken:

```json
{
  "url": "https://github.com/nixos/nixpkgs-channels.git",
  "rev": "7e5690c088a542d979afab26a5f0f60f37fe2a98",
  "date": "2020-02-28T20:42:15+01:00",
  "sha256": "1gd9giqngr64ms6gjbbhygm2c53kyrrfxs9yhc8dnsh9blhg8cg4",
  "fetchSubmodules": false,
  "deepClone": false,
  "leaveDotGit": false
}
```

Generated using:

```
nix-prefetch-git https://github.com/nixos/nixpkgs-channels.git refs/heads/nixos-unstable > ./nix/nixos-unstable.json --rev 7e5690c088a542d979afab26a5f0f60f37fe2a98
```

with a `release.nix` of:

```nix
let
  pinnedPkgs = import ./nix/pkgs-from-json.nix { json = ./nix/nixos-unstable.json; };
in
  pinnedPkgs.haskellPackages.callPackage ./default.nix { nixpkgs = pinnedPkgs; }
```

and `./nix/pkgs-from-json.nix`:

```nix
{ json }:
let
  bootstrapPkgs = import <nixpkgs> {};
  nixpkgs = builtins.fromJSON (builtins.readFile json);
  src = bootstrapPkgs.fetchFromGitHub {
    owner = "NixOS";
    repo  = "nixpkgs-channels";
    inherit (nixpkgs) rev sha256;
  };
in
  import src {}
```

Unfortunately, I get this error instead:

```
...
builder for '/nix/store/jhlxyb0jny3810zls9f9mpwmbzysji5w-cryptonite-0.26.drv' failed with exit code 1
cannot build derivation '/nix/store/k33zyqwj9hpv70kmqkawi209gmxzcvp4-ghc-8.6.5-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/k33zyqwj9hpv70kmqkawi209gmxzcvp4-ghc-8.6.5-with-packages.drv' failed
```

I stopped looking at that point. If it's working with your nixpkgs, consider pinning it to that version.

### PR DESCRIPTION
**Pull request by gvolpe**
closes #2 

Hey @willbush, would you give it a try and let me know if it works for you? I'm not sure whether I should also pin nixpkgs on my `default.nix`.

### CODE REVIEW

**Comment by gvolpe** [comment]
I checked this on a different machine with a fresh install and can confirm it works :+1:

**Comment by willbush** [comment]
I tried it yesterday and I couldn't get it to work even when I replaced all nixpkgs imports with your pinned version in each nix file. I had something come up and I wasn't able to look into it further. I'll test it again and your recent updates this evening and let you know.

**Comment by willbush** [comment]
Actually, I went ahead and pulled master and tried it, but I'm getting the same issue:

```
λ ~/code/shopping-cart-haskell/ master nix-shell
unpacking 'https://github.com/NixOS/nixpkgs-channels/archive/1fe82110feb.tar.gz'...
error: Package ‘refined-0.4.4’ in /nix/store/in95j6pwbgzr5bxncqv3iaav5nx0yik2-source/pkgs/development/haskell-modules/hackage-packages.nix:203991 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
λ ~/code/shopping-cart-haskell/ master git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
λ ~/code/shopping-cart-haskell/ master
```

Do you have `nixpkgs.config.allowBroken = true;` set by chance in your config?

**Comment by gvolpe** [comment]
Yes, I forgot to mention that. You need to set `allowBroken = true;` and it'll work. This needs to be fixed in `nixpkgs` where is mistakenly marked as broken (I'll probably do that in the next few days).

**Comment by willbush** [comment]
Ok so `echo "{ allowBroken = true; }" > ~/.config/nixpkgs/config.nix` worked for me. Perhaps this should be added to the readme or I think there is a way to override nixpkgs that's imported to do this. 

After grepping through my local cloned repos I noticed reflex-platform does something like that [here](https://github.com/reflex-frp/reflex-platform/blob/e529aa187b4370fd7c9f82701804431d2a9a4b35/default.nix#L108). However they import `nixpkgsFunc ? import ./nixpkgs` nixpkgs as a function instead of a set. I'm not good enough with nix to follow how that is being done.

**Comment by gvolpe** [comment]
I think the right thing to do is to fix it upstream in `nixpkgs`, I'll try to get it done.

**Comment by gvolpe** [comment]
https://github.com/NixOS/nixpkgs/issues/83445

**Comment by willbush** [comment]
Cool. I ought to contribute to that project as well, but I'm not really sure where to start.

**Pull request merged**
